<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <Product>MediaSuite</Product>
    <Company>MediaSuite</Company>
    <Copyright>Personal use</Copyright>
    <Version>0.1.0</Version>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
