using MediaSuite.Core.Tooling;

namespace MediaSuite.Core.Tests;

/// <summary>Stands in for 7-Zip, so the archive engine can be tested without it installed.</summary>
/// <remarks>
/// Extraction ("x ... -o&lt;dir&gt;") writes a configurable set of fake extracted files into
/// that directory; creation ("a -t&lt;type&gt; output sources... ") writes the single output
/// file. The two share one executable, so they are told apart by their first argument.
/// </remarks>
public sealed class ArchiveFakeToolRunner : IProcessRunner
{
    public List<ProcessRequest> Requests { get; } = new();

    public string? NextFailure { get; set; }

    /// <summary>File names (not paths) an extraction writes into the destination folder.</summary>
    public IReadOnlyList<string> ExtractedFileNames { get; set; } = new[] { "one.txt" };

    public IReadOnlyList<ProcessRequest> RequestsFor(string executableFragment) =>
        Requests.Where(r => r.FileName.Contains(executableFragment, StringComparison.OrdinalIgnoreCase)).ToList();

    /// <summary>Every "a" (create) call, in order — useful for checking the gzip two-step.</summary>
    public IReadOnlyList<ProcessRequest> CreateCalls =>
        Requests.Where(r => r.Arguments.Count > 0 && r.Arguments[0] == "a").ToList();

    public Task<ProcessResult> RunAsync(ProcessRequest request, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        lock (Requests)
        {
            Requests.Add(request);
        }

        if (NextFailure is { } failure)
        {
            NextFailure = null;
            return Task.FromResult(new ProcessResult(1, string.Empty, failure, TimeSpan.Zero));
        }

        var args = request.Arguments;

        if (args.Count > 0 && args[0] == "x")
        {
            var outFlag = args.FirstOrDefault(a => a.StartsWith("-o", StringComparison.Ordinal));
            var directory = outFlag?[2..] ?? ".";

            foreach (var name in ExtractedFileNames)
            {
                Write(Path.Combine(directory, name));
            }

            return Ok();
        }

        if (args.Count > 0 && args[0] == "a")
        {
            // a, -t<type>, <output>, sources..., -y — the output is always the third argument.
            Write(args[2]);
            return Ok();
        }

        return Ok();
    }

    private static Task<ProcessResult> Ok() =>
        Task.FromResult(new ProcessResult(0, string.Empty, string.Empty, TimeSpan.FromMilliseconds(1)));

    private static void Write(string path)
    {
        var directory = Path.GetDirectoryName(path);

        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(path, "generated by ArchiveFakeToolRunner");
    }
}
