using MediaSuite.Core.Tooling;

namespace MediaSuite.Core.Tests;

/// <summary>
/// Stands in for Pandoc, LibreOffice and Calibre, so the document engine can be tested
/// without any of them installed.
/// </summary>
/// <remarks>
/// The three tools disagree on where the output goes: Pandoc takes an explicit
/// <c>-o</c> flag, Calibre's <c>ebook-convert</c> takes the destination as its last
/// positional argument, and LibreOffice never takes a destination file at all — only a
/// folder — and writes under the input's own base name.
/// </remarks>
public sealed class DocumentFakeToolRunner : IProcessRunner
{
    public List<ProcessRequest> Requests { get; } = new();

    public string? NextFailure { get; set; }

    /// <summary>
    /// When set, the next LibreOffice call "succeeds" (exit code 0) but writes no file —
    /// a real failure mode: a missing import filter can leave soffice exiting clean with
    /// nothing produced, and the engine has to notice the file never landed.
    /// </summary>
    public bool NextLibreOfficeWritesNothing { get; set; }

    public IReadOnlyList<ProcessRequest> RequestsFor(string executableFragment) =>
        Requests.Where(r => r.FileName.Contains(executableFragment, StringComparison.OrdinalIgnoreCase)).ToList();

    public Task<ProcessResult> RunAsync(ProcessRequest request, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        lock (Requests)
        {
            Requests.Add(request);
        }

        if (NextFailure is { } failure)
        {
            NextFailure = null;
            return Task.FromResult(new ProcessResult(1, string.Empty, failure, TimeSpan.Zero));
        }

        var file = request.FileName;
        var args = request.Arguments;

        if (file.Contains("pandoc", StringComparison.OrdinalIgnoreCase))
        {
            Write(AfterFlag(args, "-o"));
            return Ok();
        }

        if (file.Contains("soffice", StringComparison.OrdinalIgnoreCase))
        {
            if (NextLibreOfficeWritesNothing)
            {
                NextLibreOfficeWritesNothing = false;
                return Ok();
            }

            var outdir = AfterFlag(args, "--outdir");
            var targetExtension = AfterFlag(args, "--convert-to");
            var name = Path.GetFileNameWithoutExtension(args[^1]);
            Write(Path.Combine(outdir, $"{name}.{targetExtension}"));
            return Ok();
        }

        // Calibre's ebook-convert: no flags at all, just [input, output].
        Write(args[^1]);
        return Ok();
    }

    private static string AfterFlag(IReadOnlyList<string> args, string flag)
    {
        var index = args.ToList().IndexOf(flag);
        return index >= 0 && index + 1 < args.Count ? args[index + 1] : args[^1];
    }

    private static Task<ProcessResult> Ok() =>
        Task.FromResult(new ProcessResult(0, string.Empty, string.Empty, TimeSpan.FromMilliseconds(1)));

    private static void Write(string path)
    {
        var directory = Path.GetDirectoryName(path);

        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(path, "generated by DocumentFakeToolRunner");
    }
}
