using MediaSuite.Core.Tooling;

namespace MediaSuite.Core.Tests;

/// <summary>
/// Stands in for the real tools so engines can be tested without ImageMagick, LibRaw or
/// Potrace installed — which is also the only way CI can test them.
/// </summary>
/// <remarks>
/// By default it "succeeds" and creates whatever file the command says it will write, so
/// engines that verify their own output still see a real file.
/// </remarks>
public sealed class FakeProcessRunner : IProcessRunner
{
    private readonly Func<ProcessRequest, ProcessResult>? _behaviour;

    public FakeProcessRunner(Func<ProcessRequest, ProcessResult>? behaviour = null) => _behaviour = behaviour;

    /// <summary>Every invocation, in order.</summary>
    public List<ProcessRequest> Requests { get; } = new();

    public ProcessRequest LastRequest => Requests[^1];

    /// <summary>Invocations whose executable path contains the given fragment.</summary>
    public IReadOnlyList<ProcessRequest> RequestsFor(string executableFragment) =>
        Requests.Where(r => r.FileName.Contains(executableFragment, StringComparison.OrdinalIgnoreCase)).ToList();

    public Task<ProcessResult> RunAsync(ProcessRequest request, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        lock (Requests)
        {
            Requests.Add(request);
        }

        if (_behaviour is not null)
        {
            return Task.FromResult(_behaviour(request));
        }

        CreateExpectedOutput(request);
        return Task.FromResult(new ProcessResult(0, string.Empty, string.Empty, TimeSpan.FromMilliseconds(1)));
    }

    /// <summary>
    /// Mimics the file each tool would have written: Potrace names its output with
    /// --output, dcraw_emu writes a TIFF beside its input, and ImageMagick writes to the
    /// last argument.
    /// </summary>
    private static void CreateExpectedOutput(ProcessRequest request)
    {
        if (request.Arguments.Count == 0)
        {
            return;
        }

        var outputFlag = request.Arguments.ToList().IndexOf("--output");
        if (outputFlag >= 0 && outputFlag + 1 < request.Arguments.Count)
        {
            Write(request.Arguments[outputFlag + 1]);
            return;
        }

        if (request.FileName.Contains("dcraw", StringComparison.OrdinalIgnoreCase))
        {
            Write(request.Arguments[^1] + ".tiff", "a decoded raw is larger than the copy");
            return;
        }

        Write(request.Arguments[^1]);
    }

    private static void Write(string path, string content = "generated by FakeProcessRunner")
    {
        var directory = Path.GetDirectoryName(path);

        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(path, content);
    }
}
