using MediaSuite.Core.Tooling;

namespace MediaSuite.Core.Tests;

/// <summary>Stands in for Real-ESRGAN and ImageMagick, so the upscale engine can be tested without either installed.</summary>
public sealed class UpscaleFakeToolRunner : IProcessRunner
{
    public List<ProcessRequest> Requests { get; } = new();

    public string? NextFailure { get; set; }

    public IReadOnlyList<ProcessRequest> RequestsFor(string executableFragment) =>
        Requests.Where(r => r.FileName.Contains(executableFragment, StringComparison.OrdinalIgnoreCase)).ToList();

    public Task<ProcessResult> RunAsync(ProcessRequest request, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        lock (Requests)
        {
            Requests.Add(request);
        }

        if (NextFailure is { } failure)
        {
            NextFailure = null;
            return Task.FromResult(new ProcessResult(1, string.Empty, failure, TimeSpan.Zero));
        }

        var args = request.Arguments;

        if (request.FileName.Contains("realesrgan", StringComparison.OrdinalIgnoreCase))
        {
            var index = args.ToList().IndexOf("-o");
            Write(index >= 0 && index + 1 < args.Count ? args[index + 1] : args[^1]);
        }
        else
        {
            // ImageMagick's sharpen pass, like every other ImageMagick call in this
            // codebase, ends with the output path.
            Write(args[^1]);
        }

        return Task.FromResult(new ProcessResult(0, string.Empty, string.Empty, TimeSpan.FromMilliseconds(1)));
    }

    private static void Write(string path)
    {
        var directory = Path.GetDirectoryName(path);

        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(path, "generated by UpscaleFakeToolRunner");
    }
}
